### ISSUE TITLE
:loudspeaker: The Roadmap to the next release [2021]

### ISSUE THREAD

**Issue by hangxingliu** [hangxingliu/vscode-nginx-conf-hint#24]
Because I didn't touch the Visual Studio Code extension long time. So I will do these things before I release the next version of this extension:

- [ ] Read the changes about extension authoring posted on vscode site.
- [ ] Closed the issues
- [ ] Check is this extension works well on the latest version VSCode and VSCode remote and fix the bugs
- [ ] Update the nginx instructions and documents

And if anyone has suggestions about the next version you can post under here, Thanks.
